from src.WFC.Tile import Tile
import os

class Cube(Tile):
    """一个立方体"""
    @property
    def property(self):
        return {"strength": 10000,
                "dieralect": 200}
    def build(self, points, *args, **kwargs):
        """生成一个立方体框架结构并保存为STP格式

        Args:
            points: 立方体8个角的坐标点列表，格式为[[x1,y1,z1], [x2,y2,z2], ...]
                   按照以下顺序排列：
                   [0]: 底面左前角 (x_min, y_min, z_min)
                   [1]: 底面右前角 (x_max, y_min, z_min)
                   [2]: 底面右后角 (x_max, y_max, z_min)
                   [3]: 底面左后角 (x_min, y_max, z_min)
                   [4]: 顶面左前角 (x_min, y_min, z_max)
                   [5]: 顶面右前角 (x_max, y_min, z_max)
                   [6]: 顶面右后角 (x_max, y_max, z_max)
                   [7]: 顶面左后角 (x_min, y_max, z_max)

        Returns:
            str: 生成的STP文件路径
        """
        if len(points) != 8:
            raise ValueError("立方体需要8个角点坐标")

        # 复制点坐标避免修改原始数据
        cube_points = [list(point) for point in points]

        # 生成STP格式的立方体框架结构
        stp_content = self._generate_cube_frame_stp(cube_points)

        # 保存为STP文件
        filename = kwargs.get('filename', 'cube_frame.stp')
        filepath = os.path.join(os.getcwd(), filename)

        try:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(stp_content)
            print(f"立方体框架结构已保存为: {filepath}")
            return filepath
        except Exception as e:
            print(f"保存STP文件时出错: {e}")
            return None

    def _generate_cube_frame_stp(self, points):
        """生成立方体框架的STP格式内容

        Args:
            points: 8个角点坐标

        Returns:
            str: STP格式的文件内容
        """
        # STP文件头
        stp_header = """ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('Cube Frame Structure'),'2;1');
FILE_NAME('cube_frame.stp','2024-01-01T00:00:00',('Generated by Cube class'),('Python Script'),'Unknown','Unknown','Unknown');
FILE_SCHEMA(('AUTOMOTIVE_DESIGN'));
ENDSEC;

DATA;
"""

        # 定义立方体的12条边（框架结构）
        edges = [
            # 底面4条边
            (0, 1), (1, 2), (2, 3), (3, 0),
            # 顶面4条边
            (4, 5), (5, 6), (6, 7), (7, 4),
            # 垂直4条边
            (0, 4), (1, 5), (2, 6), (3, 7)
        ]

        stp_body = ""
        entity_id = 1

        # 生成点实体
        point_entities = []
        for i, point in enumerate(points):
            x, y, z = point

            stp_body += f"#{entity_id} = CARTESIAN_POINT('P{i}',({x:.6f},{y:.6f},{z:.6f}));\n"
            point_entities.append(entity_id)
            entity_id += 1

        # 生成线段实体（框架的边）
        line_entities = []
        for i, (start_idx, end_idx) in enumerate(edges):
            start_point_id = point_entities[start_idx]
            end_point_id = point_entities[end_idx]

             # 创建向量
            vector_id = entity_id
            stp_body += f"#{vector_id} = VECTOR('V{i}',#{vector_id + 1},1.0);\n"
            entity_id += 1

            # 创建方向
            direction_id = entity_id
            start_point = points[start_idx]
            end_point = points[end_idx]
            dx = end_point[0] - start_point[0]
            dy = end_point[1] - start_point[1]
            dz = end_point[2] - start_point[2]
            length = (dx ** 2 + dy ** 2 + dz ** 2) ** 0.5
            if length > 0:
                dx, dy, dz = dx / length, dy / length, dz / length
            stp_body += f"#{direction_id} = DIRECTION('D{i}',({dx:.6f},{dy:.6f},{dz:.6f}));\n"
            entity_id += 1

            # 创建线段
            line_id = entity_id
            stp_body += f"#{line_id} = LINE('L{i}',#{start_point_id},#{vector_id});\n"
            line_entities.append(line_id)
            entity_id += 1

        # 创建几何集合
        geometric_set_id = entity_id
        line_refs = ','.join([f"#{line_id}" for line_id in line_entities])
        stp_body += f"#{geometric_set_id} = GEOMETRIC_SET('CubeFrame',({line_refs}));\n"
        entity_id += 1

        # STP文件尾
        stp_footer = "ENDSEC;\nEND-ISO-10303-21;"

        return stp_header + stp_body + stp_footer






if __name__ == "__main__":
    cube=Cube()
    print(cube.property)
    cube_points = [
        [0, 0, 0],  # 底面左前角
        [1, 0, 0],  # 底面右前角
        [1, 1, 0],  # 底面右后角
        [0, 1, 0],  # 底面左后角
        [0, 0, 1],  # 顶面左前角
        [1, 0, 1],  # 顶面右前角
        [1, 1, 1],  # 顶面右后角
        [0, 1, 1]  # 顶面左后角
    ]
    # 生成立方体框架结构并保存为STP文件
    result = cube.build(cube_points, filename='cube_frame.stp')
    if result:
        print(f"立方体框架结构已成功生成并保存到: {result}")
    else:
        print("生成立方体框架结构失败")